export const exercises = [
	[1, 'squat', 'Squat', 'Присед', 215],
	[2, 'dl', 'Deadlift', 'Тяга', 240],
	[3, 'bench', 'Bench press', 'Жим лежа', 150],
	[4, 'bench_with_band', 'Resistance band bench press', 'Жим лежа с резиной', 140],
	[5, 'press', 'Standing press', 'Жим стоя', 75],
	[6, 'good_morning', 'Good mornings', 'Наклоны', 100],
];

export const workouts = [
	{
		id: 1,
		date: '2022-05-02T09:31:23.608Z',
		sets: [
			{
				workoutId: 1,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 1,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 1,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 1,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 1,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 1,
				multiple: 4,
				reps: 4,
				weight: 120,
				isWorkSet: true,
			},
			{
				workoutId: 1,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 0,
				reps: 8,
				weight: 60,
			},
			{
				workoutId: 1,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 1,
				multiple: 3,
				reps: 8,
				weight: 90,
				isWorkSet: true,
			},
		],
	},
	{
		id: 2,
		date: '2022-05-04T09:31:23.608Z',
		sets: [
			{
				workoutId: 2,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 2,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 2,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 2,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 0,
				reps: 8,
				weight: 60,
			},
			{
				workoutId: 2,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 1,
				multiple: 3,
				reps: 8,
				weight: 90,
				isWorkSet: true,
			},
		],
	},
	{
		id: 3,
		date: '2022-05-06T09:31:23.608Z',
		sets: [
			{
				workoutId: 3,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 3,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 3,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 3,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 3,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 1,
				multiple: 4,
				reps: 4,
				weight: 120,
				isWorkSet: true,
			},
			{
				workoutId: 3,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 0,
				reps: 8,
				weight: 60,
			},
			{
				workoutId: 3,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 1,
				multiple: 3,
				reps: 8,
				weight: 90,
				isWorkSet: true,
			},
		],
	},
	{
		id: 4,
		date: '2022-05-07T09:31:23.608Z',
		sets: [
			{
				workoutId: 4,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 4,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 4,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 4,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 4,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 1,
				multiple: 4,
				reps: 4,
				weight: 120,
				isWorkSet: true,
			},
		],
	},
	{
		id: 5,
		date: '2022-05-09T09:31:23.608Z',
		sets: [
			{
				workoutId: 5,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 5,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 5,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 5,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 5,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 1,
				multiple: 4,
				reps: 4,
				weight: 120,
				isWorkSet: true,
			},
			{
				workoutId: 5,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 0,
				reps: 8,
				weight: 60,
			},
			{
				workoutId: 5,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 1,
				multiple: 3,
				reps: 8,
				weight: 90,
				isWorkSet: true,
			},
		],
	},
	{
		id: 6,
		date: '2022-05-11T09:31:23.608Z',
		sets: [
			{
				workoutId: 6,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 6,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 6,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 6,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 6,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 1,
				multiple: 4,
				reps: 4,
				weight: 120,
				isWorkSet: true,
			},
			{
				workoutId: 6,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 0,
				reps: 8,
				weight: 60,
			},
			{
				workoutId: 6,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 1,
				multiple: 3,
				reps: 8,
				weight: 90,
				isWorkSet: true,
			},
		],
	},
	{
		id: 7,
		date: '2022-05-13T09:31:23.608Z',
		sets: [
			{
				workoutId: 7,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 7,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 1,
				reps: 5,
				weight: 120,
			},
			{
				workoutId: 7,
				exerciseId: 1,
				oneRepMaxId: 1,
				order: 2,
				multiple: 3,
				reps: 5,
				weight: 170,
				isWorkSet: true,
			},
			{
				workoutId: 7,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 0,
				reps: 5,
				weight: 70,
			},
			{
				workoutId: 7,
				exerciseId: 3,
				oneRepMaxId: 3,
				order: 1,
				multiple: 4,
				reps: 4,
				weight: 120,
				isWorkSet: true,
			},
			{
				workoutId: 7,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 0,
				reps: 8,
				weight: 60,
			},
			{
				workoutId: 7,
				exerciseId: 6,
				oneRepMaxId: 6,
				order: 1,
				multiple: 3,
				reps: 8,
				weight: 90,
				isWorkSet: true,
			},
		],
	},
];
